@startuml

title 建造者模式类图

class Product

interface Builder {
    + void buildPartA()
    + void buildPartB()
    + void buildPartC()
    + Product getResult()
}

class ConcreteBuilder {
    + void buildPartA()
    + void buildPartB()
    + void buildPartC()
    + Product getResult()
}

class Director {
    - Builder builder
    + Product construct()
}

note left of Director
public Product construct() {
    builder.buildPartA();
    builder.buildPartB();
    builder.buildPartC();
    return builder.getResult();
}
end note

ConcreteBuilder ..|> Builder
ConcreteBuilder ..> Product
Director ..> Builder

@enduml