@startuml

title 组合模式类图

abstract class Component {
    + void operation()
    + void add(Component c)
    + void remove(Component c)
    + void getChild(int i)
}

class Composite {
    # Component[] children
    + void operation()
    + void add(Component c)
    + void remove(Component c)
    + void getChild(int i)
}

class Leaf {
    + void operation()
}

Component <|-- Leaf
Component <|-- Composite
Component <--o Composite : children

Component <.. Client

@enduml