@startuml

title 责任链模式类图

abstract class Handler {
    - Handler successor
    + void handlerRequest();
}

class ConcreteHandler {
}

Handler <|-- ConcreteHandler

Handler --> Handler:+successor

class Client

Client --> Handler

@enduml