@startuml

title 跨平台图像浏览系统初始设计方案类图

abstract class Image

class BmpImage
class JpgImage
class GifImage
class PngImage

BmpImage --|> Image
JpgImage --|> Image
GifImage --|> Image
PngImage --|> Image

class WindowsBmpImage
class LinuxBmpImage
class UnixBmpImage
WindowsBmpImage --|> BmpImage
LinuxBmpImage --|> BmpImage
UnixBmpImage --|> BmpImage

class WindowsJpgImage
class LinuxJpgImage
class UnixJpgImage
WindowsJpgImage --|> JpgImage
LinuxJpgImage --|> JpgImage
UnixJpgImage --|> JpgImage

class WindowsGifImage
class LinuxGifImage
class UnixGifImage
WindowsGifImage --|> GifImage
LinuxGifImage --|> GifImage
UnixGifImage --|> GifImage

class WindowsPngImage
class LinuxPngImage
class UnixPngImage
WindowsPngImage --|> PngImage
LinuxPngImage --|> PngImage
UnixPngImage --|> PngImage

@enduml